### ISSUE TITLE
Invalid Role generation with AddRole

### ISSUE THREAD

**Issue by LeChatP** [LeChatP/RootAsRole#12]
# Issue

When creating a role with insufficient parameters (no users/groups), the role created is incorrect.

## Command

`addrole test cap_dac_override -c ls`

## Result

```xml
<role name="test">
      <capabilities>
        <capability>cap_sys_admin</capability>
      </capabilities>
      <commands>
        <command>ls</command>
      </commands>
</role>
```

## Expected Result

An error, Respecting the DTD, role must have actor to have command.

**Comment by SamerW** [comment]
We need to block this operation, because roles must be assigned to users and/or groups.

**Comment by LeChatP** [comment]
Globally, addrole don't respect DTD at all.

**Comment by SamerW** [comment]
I think we need to revise the code of role manager tools.

**Comment by LeChatP** [comment]
https://github.com/SamerW/RootAsRole/commit/d596b19af857b84f2b87e798dd381d933d1ebd4a Not completely tested fix

**Comment by LeChatP** [comment]
is no longer relevant
