### ISSUE TITLE
dupplication

### ISSUE THREAD

**Issue by coolBloopers** [LeChatP/RootAsRole#3]
https://github.com/SamerW/RootAsRole/blob/f1e73b1f3483b9e030a9226a94f99a563a524389/src/capabilities.c#L197

there seems to be 2 identical tests, is this supposed to be?

**Comment by LeChatP** [comment]
I don't written these lines, but I will investigate if there's any reason for this condition

**Comment by LeChatP** [comment]
is no longer relevant
