### ISSUE TITLE
RHEL: capable not working

### ISSUE THREAD

**Issue by colonelgeil** [LeChatP/RootAsRole#40]
**Issue**
I tried RootAsRole on an RHEL 8 Host. 
The tool capable only gives empty output:

Here's all capabilities intercepted for this program :

WARNING: These capabilities aren't mandatory, but can change the behavior of tested program.
WARNING: CAP_SYS_ADMIN is rarely needed and can be very dangerous to grant

I think it does not work with the RHEL kernel ?

**To Reproduce**
execute the command on rhel, example  capable yum update -y
.

**Desktop (please complete the following information):**
 - OS: Redhat Enterprise Linux
 - Version 8

**Comment by LeChatP** [comment]
Hello, thank you for this excellent issue! :smiley: 
I tried rhel8 and rhel9; it seems that `capable` works without arguments. However, when using arguments, the filter is not working as expected and is filtering everything. I need deeper verifications.
