### ISSUE TITLE
RHEL: chsr not working correctly

### ISSUE THREAD

**Issue by colonelgeil** [LeChatP/RootAsRole#41]
**Describe the bug**
Saving created Roles via chsr is not working.

Error Message:
unable to retrieve allow-root

tried it with several users (root, personal account)

**Desktop (please complete the following information):**
 - OS: Redhat Enterprise Linux
 - Version 8

**Comment by LeChatP** [comment]
chsr is currently in its early development stage. I'm currently working on a better design for the upcoming version.
